#! /usr/bin/env bash

if [[ "Darwin" = "$(uname)" ]]; then
    # if pgrep Emacs | xargs ps | grep 'bg-daemon.*=.*term' > /dev/null; then
    #     /Applications/Emacs.app/Contents/MacOS/Emacs --daemon=frame
    # fi
    exec /Applications/Emacs.app/Contents/MacOS/bin/emacsclient -c --socket-name=frame
else
    exec emacsclient -c --socket-name frame
fi
